
spring:
  datasource:
      url: jdbc:mysql://localhost/travelmediarest
      username: root
      password: bs23
logging:
  level:
    tacos: WARN
---

greeting:
  welcome : You are using ${spring.application.name}.
